FanPosts/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views

urlpatterns = [
    path('', views.home),
    path('main/', views.main),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sign/', include('sign.urls'))
]

sign/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.urls import path
from .views import *

urlpatterns = [
    path('login/', LoginView.as_view(template_name='sign/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='sign/logout.html'), name='logout'),
    path('signup/', BaseRegisterView.as_view(), name='signup'),
    path('profile/', Profile.as_view(), name='profile'),
    path('password/change/', PasswordChangeView.as_view(template_name='sign/password_change.html'), name='password_change'),
    path('password/change/done/', PasswordChangeDoneView.as_view(template_name='sign/password_change_done.html')),
    path('profile/<int:pk>/', ProfileDetail.as_view(), name='profile_detail'),
    path('profile/<int:pk>/edit/', ProfileUpdate.as_view(), name='profile_edit'),
    path('profile/<int:pk>/delete/', ProfileDelete.as_view(), name='profile_delete'),
    path('code/<str:user>', GetCode.as_view(), name='code'),
]

board/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.urls import reverse


class Category(models.Model):
    category_name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, related_name='categories')

    def __str__(self):
        return self.category_name


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post_title = models.CharField(max_length=256)
    post_content = RichTextField()
    post_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    date_creation = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.post_title

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class Reply(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reply_text = models.TextField()
    date_creation = models.DateTimeField(auto_now_add=True)
    reply_accept = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user} ({self.reply_text[:30]}...)'

    def get_absolute_url(self):
        return reverse('post_reply_detail', args=[str(self.pk)])


class OneTimeCode(models.Model):
    user = models.CharField(max_length=256)
    code = models.CharField(max_length=10)

sign/models.py
from django.db import models

# Create your models here.

sign/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class BaseRegisterForm(UserCreationForm):
    email = forms.EmailField(label="Email")
    username = forms.CharField(label="Имя")

    class Meta:
        model = User
        fields = ("username",
                  "email",
                  "password1",
                  "password2",)


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]

sign/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from board.filters import PostFilter
from .forms import BaseRegisterForm, UserForm
from django.shortcuts import redirect, render
from board.models import *
from django.core.mail import send_mail
from FanPosts import settings
from string import hexdigits
import random


class BaseRegisterView(CreateView):
    model = User
    template_name = 'sign/signup.html'
    form_class = BaseRegisterForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = BaseRegisterForm()
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            active = form.save(commit=False)
            active.is_active = False
            active.save()
        return redirect('code', request.POST['username'])


class GetCode(CreateView):
    template_name = 'sign/code.html'

    def get_context_data(self, **kwargs):
        if not OneTimeCode.objects.filter(user=self.kwargs.get('user')).exists():
            code = ''.join(random.sample(hexdigits, 5))
            OneTimeCode.objects.create(user=self.kwargs.get('user'), code=code)
            user = User.objects.get(username=self.kwargs.get('user'))
            send_mail(
                subject=f'Код активации',
                message=f'Код активации аккаунта: {code}',
                from_email=settings.DEFAULT_FROM_EMAIL,
                recipient_list=[user.email],
            )

    def post(self, request, *args, **kwargs):
        if 'code' in request.POST:
            user = request.path.split('/')[-1]
            if OneTimeCode.objects.filter(code=request.POST['code'], user=user).exists():
                User.objects.filter(username=user).update(is_active=True)
                OneTimeCode.objects.filter(code=request.POST['code'], user=user).delete()
            else:
                return render(self.request, 'sign/invalid_code.html')
        return redirect('login')


class Profile(LoginRequiredMixin, TemplateView):
    template_name = 'sign/profile.html'

    def get_context_data(self, **kwargs):
        queryset = Reply.objects.filter(post__author_id=self.request.user.pk).order_by('-date_creation')
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset, request=self.request.user.pk)
        return context


class ProfileDetail(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'sign/profile_detail.html'
    context_object_name = 'user'


class ProfileUpdate(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserForm
    template_name = 'sign/profile_update.html'
    context_object_name = 'user'
    success_url = '/sign/profile/'

    def dispatch(self, request, *args, **kwargs):
        user = self.get_object()
        if user != self.request.user:
            return render(self.request, 'sign/403.html')
        return super(ProfileUpdate, self).dispatch(request, *args, **kwargs)


class ProfileDelete(LoginRequiredMixin, DeleteView):
    model = User
    template_name = 'sign/profile_delete.html'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        user = self.get_object()
        if user != self.request.user:
            return render(self.request, 'sign/403.html')
        return super(ProfileDelete, self).dispatch(request, *args, **kwargs)

templates/sign/code.html
{% extends "default.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/login.css' %}"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
<script href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
<script href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Активация аккаунта</title>
</head>
<body>
    <div class="wrapper">
        <div class="logo">
            <img src="https://fogsoft.com/wp-content/uploads/2017/07/user-logo.png" alt="">
        </div>
        <div class="text-center mt-4 name">
            Активация аккаунта
        </div>
        <form class="p-3 mt-3" method="post">
            {% csrf_token %}
            <div class="form-field d-flex align-items-center">
                <span class="fa fa-power-off" aria-hidden="true"></span>
                <label>
                    <input class="text" type="text" name="code" placeholder="Введите код активации">
                </label>
            </div>
            {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger">
                        <small>{{ error|escape }}</small>
                        </div>
                        {% endfor %}
                    {% endfor %}
                        {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                        <small>{{ error|escape }}</small>
                        </div>
                    {% endfor %}
            {% endif %}
            <button class="btn mt-3">Подтвердить</button>
        </form>
    </div>
</body>
</html>
{% endblock %}

templates/sign/invalid_code.html
{% extends "default.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/login.css' %}"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
<script href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
<script href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Активация аккаунта</title>
</head>
<body>
    <div class="wrapper">
        <div class="logo">
            <img src="https://fogsoft.com/wp-content/uploads/2017/07/user-logo.png" alt="">
        </div>
        <div class="text-center mt-4 name">
            Активация аккаунта
        </div>
        <form class="p-3 mt-3">
            <h5> Неверный код активации </h5>
            <input type="button" onclick="history.back();" class="btn mt-3" value="Вернуться к вводу кода"/>
        </form>
    </div>
</body>
</html>
{% endblock %}

templates/sign/login.html
{% extends "default.html" %}
{% load crispy_forms_filters %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/login.css' %}"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
<script href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
<script href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Вход</title>
</head>
<body>
    <div class="wrapper">
        <div class="logo">
            <img src="https://fogsoft.com/wp-content/uploads/2017/07/user-logo.png" alt="">
        </div>
        <div class="text-center mt-4 name">
            Вход
        </div>
        <form class="p-3 mt-3" method="post">
            {% csrf_token %}
            <div class="form-field d-flex align-items-center">
                <span class="fa fa-user"></span>
                <label for="username"></label><input autocomplete="off" type="text" name="username" id="username" placeholder="Имя или Email">
            </div>
            <div class="form-field d-flex align-items-center">
                <span class="fas fa-key"></span>
                <label for="pwd"></label><input autocomplete="off" type="password" name="password" id="pwd" placeholder="Пароль">
            </div>
            {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger">
                        <small>{{ error|escape }}</small>
                        </div>
                        {% endfor %}
                    {% endfor %}
                        {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                        <small>{{ error|escape }}</small>
                        </div>
                    {% endfor %}
            {% endif %}
            <button class="btn">Войти</button>
        </form>
        <div class="text-center fs-6">
            <a style="font-size: 16px; " href="/accounts/password/reset/">Забыли пароль?</a> &ensp; <a style="font-size: 16px; " href='{% url "signup" %}'>Регистрация</a>
        </div>
    </div>
</body>
</html>
{% endblock %}

templates/sign/logout.html
{% extends "default.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/login.css' %}"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
<script href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
<script href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Выход</title>
</head>
<body>
    <div class="wrapper">
        <div class="logo">
            <img src="https://fogsoft.com/wp-content/uploads/2017/07/user-logo.png" alt="">
        </div>
        <div class="text-center mt-4 name">
            Вы вышли из системы
        </div>
        <div class="p-3 mt-3">
            <h6>Чтобы продолжать пользоваться всеми возможностями</h6>
            <h5><span style="color: orangered; ">Bulletin board </span></h5>
            <br>
            <a href='{% url "login" %}' class="btn mt-3"><h5>Авторизуйтесь</h5></a>
        </div>
    </div>
</body>
</html>
{% endblock %}

templates/sign/password_change.html
{% extends "default.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/login.css' %}"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
<script href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
<script href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Изменение пароля</title>
</head>
<body>
    <div class="wrapper">
        <div class="logo">
            <img src="https://fogsoft.com/wp-content/uploads/2017/07/user-logo.png" alt="">
        </div>
        <div class="text-center mt-4 name">
            Изменение пароля
        </div>
        <form class="p-3 mt-3" method="post">
            {% csrf_token %}
            <div class="form-field d-flex align-items-center">
                <span class="fas fa-key"></span>
                <label for="id_old_password"></label>
                <input type="password" name="old_password" autocomplete="current-password" autofocus="" class="textinput textInput form-control" required="" id="id_old_password" placeholder="Введите старый пароль">
            </div>
            <div class="form-field d-flex align-items-center">
                <span class="fas fa-key"></span>
                <label for="id_new_password1"></label>
                <input type="password" name="new_password1" autocomplete="new-password" class="textinput textInput form-control" required="" id="id_new_password1" aria-autocomplete="list" placeholder="Ведите новый пароль">
            </div>
            <div class="form-field d-flex align-items-center">
                <span class="fas fa-key"></span>
                <label for="id_new_password2"></label>
                <input type="password" name="new_password2" autocomplete="new-password" class="textinput textInput form-control" required="" id="id_new_password2" placeholder="Подтвердите пароль">
            </div>
            {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger">
                        <small>{{ error|escape }}</small>
                        </div>
                        {% endfor %}
                    {% endfor %}
                        {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                        <small>{{ error|escape }}</small>
                        </div>
                    {% endfor %}
            {% endif %}
            <button class="btn mt-3">Подтвердить</button>
        </form>
    </div>
</body>
</html>
{% endblock %}

templates/sign/password_change_done.html
{% extends "default.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/login.css' %}"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
<script href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
<script href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Изменение пароля</title>
</head>
<body>
    <div class="wrapper">
        <div class="logo">
            <img src="https://fogsoft.com/wp-content/uploads/2017/07/user-logo.png" alt="">
        </div>
        <div class="text-center mt-4 name">
            Изменение пароля
        </div>
        <form class="p-3 mt-4">
            <h5> Вы успешно изменили свой пароль </h5>
            <a href="{% url 'profile' %}" class="btn mt-3"><font size="4">Вернуться в профиль</font></a>
        </form>
    </div>
</body>
</html>
{% endblock %}

templates/sign/profile.html
{% extends "default.html" %}
{% load static %}
{% block content %}
<h4 style="margin-top: 40px">Личный кабинет</h4>
<div class="page-content page-container" id="page-content">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}"/>
    <div class="no-padding" style="margin-top: 20px">
        <div class="row container d-flex justify-content-center">
            <div class="col-lg-6 col-xlg-4">
                <div class="card">
                    <div class="card-body little-profile text-center">
                        <div ><p><h1><span class="icon"><i class="fa fa-user"></i></span></h1></div>
                        <h2 class="m-b-0 font-medium "><span style="color: orangered;">{{ user.username }}</span>
                        </h2>
                        <br>
                        <div class="text-center">
                            <div class="row">
                                 <div class="col-lg-6 col-md-6 p-20 b-r">
                                    <h6 class="m-b-0 font-medium btn-rounded">Имя:</h6><small>{{ user.first_name|default:"Нет данных" }}</small>
                                </div>
                                <div class="col-lg-6 col-md-6 p-20 b-r">
                                    <h6 class="m-b-0 font-medium btn-rounded">Фамилия:</h6><small>{{ user.last_name|default:"Нет данных" }}</small>
                                </div>

                            </div>
                        </div>
                        <div class="text-center">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 p-20 b-r">
                                    <h6 class="m-b-0 font-medium btn-rounded">Регистрация:</h6><small>{{ user.date_joined }}</small>
                                </div>
                                <div class="col-lg-6 col-md-6 p-20 b-r">
                                    <h6 class="m-b-0 font-medium btn-rounded">Email:</h6><small>{{ user.email }}</small>
                                </div>
                            </div>
                        </div>
                        <div class="text-center">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 p-20 b-r">
                                    <h6 class="m-b-0 font-medium btn-rounded"><a href="{% url 'user_posts_list' request.user.id %}" style="text-decoration: none;">Объявления</a></h6><small>{{ user.post_set.count }}</small>
                                </div>
                                <div class="col-lg-6 col-md-6 p-20">
                                    <h6 class="m-b-0 font-medium btn-rounded"><a href="{% url 'user_replies' %}" style="text-decoration: none;">Отклики</a></h6><small>{{ filter.qs.count }}</small>
                                </div>
                            </div>
                        </div>
                    <div class="text-center">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 p-20 b-r">
                                    <h6 class="m-b-0 font-medium btn-rounded"><a href="{% url 'password_change' %}" style="text-decoration: none; color: brown;"><span class="icon"><i class="fa fa-key"></i></span>&ensp;Изменить пароль</a></h6>
                                </div>
                                <div class="col-lg-6 col-md-6 p-20 b-r">
                                    <h6 class="m-b-0 font-medium btn-rounded"><a href="{% url 'logout' %}" style="text-decoration: none; color: blue;"><span class="icon"><i class="fa fa-sign-out"></i></span>&ensp;Выйти аккаунта</a></h6>
                                </div>
                            </div>
                        </div>
                    <div class="text-center">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 p-20 b-r">
                                    <h6 class="m-b-0 font-medium btn-rounded"><a href="{% url 'profile_edit' user.id %}" style="text-decoration: none; color: forestgreen;"><span class="icon"><i class="fa fa-wrench"></i></span>&ensp;Изменить профиль</a></h6>
                                </div>
                                <div class="col-lg-6 col-md-6 p-20 b-r">
                                    <h6 class="m-b-0 font-medium btn-rounded"><a href="{% url 'profile_delete' user.id %}" style="text-decoration: none; color: red;"><span class="icon"><i class="fa fa-trash-o"></i></span>&ensp;Удалить аккаунт</a></h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/sign/profile_delete.html
{% extends "default.html" %}
{% block title %}
<title>Удаление аккаунта</title>
{% endblock title %}
{% block content %}
    <h3 style="margin-top: 40px"><span style="color: orangered;">Вы уверены, что хотите удалить свой аккаунт?</span></h3>
    <h5 style="margin-top: 20px">После подтверждения ваш аккаунт будет удален и восстановить его будет невозможно!</h5>
    <div style="margin-top: 30px">
    <form method="POST">
        {% csrf_token %}
        <input style="margin-right: 20px" class="btn btn-success btn-sm" type="button" onclick="history.back();" value="Отмена"/>
        <input class="btn btn-danger btn-sm" type="submit" value="Подтвердить">
    </form>
    </div>
{% endblock content %}

templates/sign/profile_detail.html
{% extends "default.html" %}
{% load static %}
{% block content %}
<div style="margin-top: 30px" class="page-content page-container" id="page-content">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}"/>
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-lg-6 col-xlg-4">
                <div class="card">
                    <div class="card-body little-profile text-center">
                        <div ><p><h1><span class="icon"><i class="fa fa-user"></i></span></h1></div>
                        <h2 class="m-b-0 font-medium "><span style="color: orangered;">{{ user.username }}</span>
                        </h2>
                        <br>
                        <div class="text-center">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 p-20 b-r">
                                    <h6 class="m-b-0 font-medium btn-rounded">Имя:</h6><small>{{ user.first_name|default:"Нет данных" }}</small>
                                </div>
                                <div class="col-lg-6 col-md-6 p-20 b-r">
                                    <h6 class="m-b-0 font-medium btn-rounded">Фамилия:</h6><small>{{ user.last_name|default:"Нет данных" }}</small>
                                </div>
                            </div>
                        </div>
                        <div class="text-center">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 p-20 b-r">
                                    <h6 class="m-b-0 font-medium btn-rounded">Регистрация:</h6><small>{{ user.date_joined }}</small>
                                </div>
                                <div class="col-lg-6 col-md-6 p-20 b-r">
                                    <h6 class="m-b-0 font-medium btn-rounded"><a href="{% url 'user_posts_list' user.id %}" style="text-decoration: none;">Объявления</a></h6><small>{{ user.post_set.count }}</small>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/sign/profile_update.html
{% extends "default.html" %}
{% load crispy_forms_filters %}
{% block title %}
    <title>Редактирование профиля</title>
{% endblock title %}
{% block content %}
    <div style="margin-top: 30px">
    <h4>Редактирование профиля</h4>
    <h3><span style="color: orangered;">{{ object }}</span></h3>
    </div>
<div class="d-flex justify-content-center" style="margin-top: 30px">
    <div class="row">
        <div class="col-lg-12 text-center" style="width: 300px">
            <form action="" method="post">
                {% csrf_token %}
            <div id="div_id_username" class="form-group"> <label for="id_username" class=" requiredField">
                Логин<span class="asteriskField">*</span> </label>
                <div> <input type="text" name="username" value='{{ user.username }}' maxlength="150" class="textinput textInput form-control" required="" id="id_username">
                    <small id="hint_id_username" class="form-text text-muted"></small>
                </div>
            </div>
                <div id="div_id_first_name" class="form-group"> <label for="id_first_name" style="margin-top: 5px">
                Имя
            </label>
                    <div>
                        <input type="text" name="first_name" maxlength="150" class="textinput textInput form-control" id="id_first_name" value='{{ user.first_name }}'>
                    </div>
                </div>
                <div id="div_id_last_name" class="form-group"> <label for="id_last_name" style="margin-top: 5px">
                Фамилия
            </label>
                    <div>
                        <input type="text" name="last_name" maxlength="150" class="textinput textInput form-control" id="id_last_name" value='{{ user.last_name }}'>
                    </div>
                </div>
                <div id="div_id_email" class="form-group"> <label for="id_email" style="margin-top: 5px">
                Email<span class="asteriskField">*</span></label>
                <div>
                    <input type="email" name="email" maxlength="254" class="emailinput form-control" id="id_email" value='{{ user.email }}'>
                </div>
            </div>
                <div style="margin-top: 10px">
                <input class="btn btn-primary btn-sm" type="submit" value="Сохранить">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/sign/signup.html
{% extends "default.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/login.css' %}"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
<script href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
<script href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
</head>
<body>
    <div class="wrapper">
        <div class="logo">
            <img src="https://fogsoft.com/wp-content/uploads/2017/07/user-logo.png" alt="">
        </div>
        <div class="text-center mt-4 name">
            Регистрация
        </div>
        <form class="p-3 mt-3" method="post">
            {% csrf_token %}
            <div class="form-field d-flex align-items-center">
                <span class="fa fa-user-plus" aria-hidden="true"></span>
                <label>
                    <input class="text" type="text" name="username" placeholder="Имя">
                </label>
            </div>
            <div class="form-field d-flex align-items-center">
                <span class="fa fa-envelope" aria-hidden="true"></span>
                <label>
                    <input class="text email" type="email" name="email" placeholder="Email">
                </label>
            </div>
            <div class="form-field d-flex align-items-center">
                <span class="fas fa-key"></span>
                <label>
                    <input class="text" type="password" name="password1" placeholder="Пароль">
                </label>
            </div>
            <div class="form-field d-flex align-items-center">
                <span class="fas fa-key"></span>
                <label>
                    <input class="text" type="password" name="password2" placeholder="Подтвердите пароль">
                </label>
            </div>
            {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger">
                        <small>{{ error|escape }}</small>
                        </div>
                        {% endfor %}
                    {% endfor %}
                        {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                        <small>{{ error|escape }}</small>
                        </div>
                    {% endfor %}
            {% endif %}
            <button class="btn mt-3">Регистрация</button>
        </form>
        <div class="text-center fs-6">
            <p>Уже есть аккаунт? <a style="font-size: 16px; " href="{% url 'login' %}"> Вход</a></p>
        </div>
    </div>
</body>
</html>
{% endblock %}